# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "marksvc/fwtest-u2004"
  config.vm.define :"testing"

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 1
    v.gui = true
    # Enable 3D acceleration and more video RAM for larger displays.
    v.customize ["modifyvm", :id, "--accelerate3d", "on"]
    v.customize ["modifyvm", :id, "--vram", "128"]
  end

  config.vm.provision "file", source: "../../development/dot-gdbinit", destination: "~/.gdbinit"

  config.vm.provision "shell", privileged: false, inline: <<~SHELL
    set -xueo pipefail
    # Changes since basebox
    tee -a ~/.pam_environment >/dev/null <<< 'LANGUAGEFORGESERVER=-qa.languageforge.org'
    # 'export ' shouldn't be on the lines. .pam_environment is not shell.
    perl -pi -e 's/export //'  ~/.pam_environment

    sudo apt-get update
    sudo apt-get --assume-yes install keyman

    echo Provisioning finished successfully.
  SHELL
end
