# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "fwtest-u1804"
  config.vm.box_url = "http://linux.lsdev.sil.org/vagrant/fwtest-u1804/fwtest-u1804.json"
  config.vm.define :"testing"

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 1
    v.gui = true
    # Enable 3D acceleration and more video RAM for larger displays.
    v.customize ["modifyvm", :id, "--accelerate3d", "on"]
    v.customize ["modifyvm", :id, "--vram", "128"]
  end

  config.vm.provision "file", source: "../../development/dot-gdbinit", destination: "~/.gdbinit"

  config.vm.provision "shell", privileged: false, inline: <<~SHELL
    set -ueo pipefail
    # Changes since basebox
	tee -a ~/.pam_environment >/dev/null <<< 'LANGUAGEFORGESERVER=-qa.languageforge.org'

    echo Provisioning finished successfully.
  SHELL
end
