# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "fwtest-w1604"
  config.vm.box_url = "http://linux.lsdev.sil.org/vagrant/fwtest-w1604/fwtest-w1604.json"
  config.vm.define :"testing"

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 1
    v.gui = true
  end

  # Turn off auto-dowloading of available packages, until this change is made in the base box.
  config.vm.provision "shell", inline: 'sudo perl -pi -e "/APT::Periodic::Download-Upgradeable-Packages/ && s/1/0/" /etc/apt/apt.conf.d/20auto-upgrades /etc/apt/apt.conf.d/10periodic'

  # Fix too many comment characters in /etc/apt/sources.list, until this change is made in the base box.
  config.vm.provision "shell", inline: 'sudo perl -pi -e "/^##deb.*linux.lsdev.sil.org.*xenial-experimental/ && s/^##/#/" /etc/apt/sources.list'

  config.vm.provision "file", source: "../dot-gdbinit", destination: "~/.gdbinit"
end
