# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "marksvc/fwtest-w2004"
  config.vm.define :"testing"

  config.vm.provider "virtualbox" do |v|
    v.memory = ENV['FWTEST_RAM'] || "2048"
    v.cpus = 2
    v.gui = true
    # Enable 3D acceleration and more video RAM for larger displays.
    v.customize ["modifyvm", :id, "--accelerate3d", "on"]
    v.customize ["modifyvm", :id, "--vram", "128"]
  end

  config.vm.provision "shell", privileged: false, inline: <<~SHELL
    set -xueo pipefail

    # Changes since basebox
    # More needed keyboard setting. Wait until desktop is loaded.
    sleep 30s
    gsettings set org.gnome.desktop.input-sources sources \
      "[('xkb', 'us'), ('xkb', 'us+dvorak'), ('xkb', 'il'), ('xkb', 'ru'), ('ibus', 'libpinyin'), ('ibus', 'table:thai')]"
    echo "The vagrant guest will benefit from a reboot now, after the keyboard setting."

    echo "Provisioning finished successfully."
  SHELL
end
