#!/bin/bash

# fw-build-all
#
# Usage: fwrepo/fw$ fw-build-all
#
# Original author: MarkS 2013-08-22

program_name=$(basename "$0")

/usr/bin/time -f "$program_name: Total time elapsed %E." cat <(. environ && cd Build && ./build /v:m )

echo $program_name: Finished at $(date +"%F %T").
