#!/bin/bash

# fw-build-recent
#
# Rebuild projects with .cs files modified recently.
# Usage: fwrepo/fw$ fw-build-recent [minutes_ago]
#
# Original author: MarkS 2013-08-14

program_name=$(basename "$0")
minutes_ago=${1:-30}
changed_files=$(find Src -mmin -$minutes_ago -name \*.cs)
changed_dirs=$(for file in $changed_files; do
	dirname "$file"
done | sort -u)
changed_dirs_with_projects=$(for dir in $changed_dirs; do
	[ -e "$dir"/*.csproj ] && echo $dir
done)
/usr/bin/time -f "$program_name: Total time elapsed %E." cat <(for dir in $changed_dirs_with_projects; do
	(. environ && cd "$dir" && xbuild || (echo "$program_name: Error building project $(basename "$dir"). Continuing ..."; sleep 5s))
done)
projects=$(for dir in $changed_dirs_with_projects; do
	basename "$dir"
done)
echo $program_name: Finished at $(date +"%F %T").
echo $program_name: Built projects: $projects
