#!/bin/bash

# pbuilder hook for adding distro name to package version
#
# Neil Mayhew - 2010-12-08

TYPE=$(lsb_release -si)
DIST=$(lsb_release -sc)
USER=$(id -un)
HOST=$(uname -n)

export DEBFULLNAME="pbuilder"
export DEBEMAIL="$USER@$HOST"

cd /tmp/buildd/*/
if [ "$(cat debian/source/format)" == "3.0 (quilt)" ]; then
	VERSION=$(dpkg-parsechangelog --show-field=Version)
	if [[ $VERSION == *"-"* ]]; then
		SEP="+"
	else
		SEP="-"
	fi
else
	SEP="+"
fi

debchange --local=${SEP}${DIST} "Build for $DIST"
debchange --release --distribution=$DIST ""
