#!/bin/bash

# pbuilder hook for adding distro name to package version
#
# Neil Mayhew - 2010-12-08

TYPE=$(lsb_release -si)
DIST=$(lsb_release -sc)
USER=$(id -un)
HOST=$(uname -n)

cd /tmp/buildd/*/

if [ "$(dpkg-parsechangelog --show-field=Distribution)" = "UNRELEASED" ]; then
	unset DEBFULLNAME
	export DEBEMAIL="$(dpkg-parsechangelog --show-field=Maintainer)"
else
	export DEBFULLNAME="pbuilder"
	export DEBEMAIL="$USER@$HOST"
fi

dch --local=+$DIST --nomultimaint "Build for $DIST"
dch --release --distribution=$DIST --nomultimaint ""
