#!/bin/bash

# Sign source and binary packages.
# Usage: ./sign-packages CHANGES_FILES...

set -ueo pipefail

which debsign >/dev/null || { echo Error: Missing debsign command. Install package devscripts. ; exit 1 ; }

. $(dirname "$0")/pbuilder/releasepackage.config

for changesfile; do
	debsign --re-sign $DEBSIGNKEY $changesfile
done
