# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/precise64"
  config.vm.define :"development"
  config.vm.hostname = "vagrant-ubuntu-1204-development"

  config.vm.provider "virtualbox" do |v|
    v.memory = 3072
    v.cpus = 2
    # Uncomment the v.gui line to gain access to this box through VirtualBox
    v.gui = true
  end

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provision
  config.vm.provision "file", source: "~/.gitconfig", destination: ".gitconfig"
  config.vm.provision "shell", inline: 'sudo apt-get -y install git; [ -n "$(git config --get fwinit.gerrituser)" ] || { echo ERROR Cannot provision without gerrit username. To fix, on your host machine execute the following command and then re-provision: git config --global fwinit.gerrituser YOUR_GERRIT_USERNAME && exit 1; }', privileged: false
  # Key file for uploading to gerrit
  config.vm.provision "file", source: "~/.ssh/id_rsa", destination: "~/.ssh/id_rsa"
  config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/id_rsa.pub"
  config.vm.provision "shell", inline: "sudo apt-get update && sudo DEBIAN_FRONTEND=noninteractive apt-get install -y ubuntu-desktop"
  # Enable automatic login
  config.vm.provision "shell", inline: "echo -e 'autologin-user=vagrant\nautologin-user-timeout=0' |sudo tee -a /etc/lightdm/lightdm.conf"
  config.vm.provision "shell", path: "../provision-fw-dev-machine", privileged: false
end
