# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "marksvc/fwdev-w1604"
  config.vm.define :"development"

  config.vm.provider "virtualbox" do |v|
    v.memory = 3584
    v.cpus = 4
    v.gui = true
  end

  config.vm.provision "file", source: "../dot-gdbinit", destination: "~/.gdbinit"
  config.vm.provision "file", source: "~/.ssh/id_rsa", destination: "~/.ssh/id_rsa"
  config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/id_rsa.pub"
end
